'use strict';

/**
 * manifest.js — pure, environment-free logic for the "Publish to GitHub" flow.
 *
 * Decides what a publish should upload from a local mod folder, and generates
 * the housekeeping files (.gitignore / .gitattributes) that keep a published
 * repo sane across platforms. No fs / electron / git here: the desktop layer
 * walks the folder and hands plain {path, bytes} entries in, so this stays
 * trivially unit-testable in plain Node.
 */

const DEFAULT_IGNORE_NAMES = [
  '.git', 'node_modules', '.studio-local', '.DS_Store', 'Thumbs.db', '.idea', '.vscode'
];

// Path-prefix ignores (vs. single segment names above). GitHub refuses to let a
// classic PAT push anything under .github/workflows/ without the elevated
// `workflow` scope, so we leave CI config out of a publish by default — a mod
// author sharing their work almost never needs the inherited build pipeline.
const DEFAULT_IGNORE_PATHS = [
  '.github/workflows'
];

const LARGE_FILE_WARN_BYTES = 25 * 1024 * 1024;    // warn on any single file >= 25 MB
const LARGE_TOTAL_WARN_BYTES = 100 * 1024 * 1024;  // warn on a total payload >= 100 MB

/**
 * True when any path segment matches an ignored name (so ignoring a directory
 * also ignores everything beneath it).
 */
function isIgnored(relPath, ignoreNames) {
  const names = ignoreNames || DEFAULT_IGNORE_NAMES;
  const rel = String(relPath || '');
  const segments = rel.split('/');
  for (let i = 0; i < segments.length; i += 1) {
    if (names.indexOf(segments[i]) !== -1) {
      return true;
    }
  }
  for (let j = 0; j < DEFAULT_IGNORE_PATHS.length; j += 1) {
    const prefix = DEFAULT_IGNORE_PATHS[j];
    if (rel === prefix || rel.indexOf(prefix + '/') === 0) {
      return true;
    }
  }
  return false;
}

/**
 * @param {Array<{path:string, bytes:number}>} entries
 * @returns {{included:Array, excluded:Array, totalBytes:number, warnings:Array}}
 */
function buildManifest(entries, options) {
  const opts = options || {};
  const ignoreNames = opts.ignoreNames || DEFAULT_IGNORE_NAMES;
  const included = [];
  const excluded = [];
  let totalBytes = 0;
  const warnings = [];

  (entries || []).forEach(function (entry) {
    const relPath = entry && entry.path ? String(entry.path) : '';
    const bytes = entry && Number.isFinite(entry.bytes) ? entry.bytes : 0;
    if (!relPath) {
      return;
    }
    if (isIgnored(relPath, ignoreNames)) {
      excluded.push({ path: relPath, bytes: bytes, reason: 'ignored' });
      return;
    }
    included.push({ path: relPath, bytes: bytes });
    totalBytes += bytes;
    if (bytes >= LARGE_FILE_WARN_BYTES) {
      warnings.push({ code: 'large_file', path: relPath, bytes: bytes });
    }
  });

  if (totalBytes >= LARGE_TOTAL_WARN_BYTES) {
    warnings.push({ code: 'large_total', bytes: totalBytes });
  }
  included.sort(function (a, b) { return a.path.localeCompare(b.path); });

  return { included: included, excluded: excluded, totalBytes: totalBytes, warnings: warnings };
}

function gitignoreContents() {
  return [
    '# Generated by Dendry Mod Studio publish',
    'node_modules/',
    '.DS_Store',
    'Thumbs.db',
    '.studio-local/',
    ''
  ].join('\n');
}

function gitattributesContents() {
  return [
    '# Generated by Dendry Mod Studio publish — keep text diffs sane cross-platform',
    '* text=auto eol=lf',
    '*.dry text',
    ''
  ].join('\n');
}

/**
 * Normalizes a folder/display name into a GitHub-legal repo name the SAME way
 * for both create and lookup, so a retry can find the repo a previous attempt
 * created. GitHub maps disallowed characters (spaces, slashes, …) to dashes;
 * we collapse runs to a single dash and trim edge dashes. The result only
 * contains [A-Za-z0-9._-], which GitHub accepts verbatim — so createRepo(name)
 * and getRepo(name) stay consistent (e.g. "Demo Mod" -> "Demo-Mod").
 */
function normalizeRepoName(name) {
  const cleaned = String(name == null ? '' : name)
    .trim()
    .replace(/[^A-Za-z0-9._-]+/g, '-')
    .replace(/^[-.]+/, '')
    .replace(/[-.]+$/, '');
  return cleaned || 'mod';
}

/**
 * GitHub "noreply" commit email derived from the authenticated user, so authors
 * never have to configure a git identity by hand.
 */
function noreplyEmail(user) {
  const login = user && user.login ? String(user.login) : 'user';
  const id = user && (user.id || user.id === 0) ? String(user.id) : '0';
  return id + '+' + login + '@users.noreply.github.com';
}

const api = {
  DEFAULT_IGNORE_NAMES: DEFAULT_IGNORE_NAMES,
  DEFAULT_IGNORE_PATHS: DEFAULT_IGNORE_PATHS,
  LARGE_FILE_WARN_BYTES: LARGE_FILE_WARN_BYTES,
  LARGE_TOTAL_WARN_BYTES: LARGE_TOTAL_WARN_BYTES,
  isIgnored: isIgnored,
  buildManifest: buildManifest,
  gitignoreContents: gitignoreContents,
  gitattributesContents: gitattributesContents,
  normalizeRepoName: normalizeRepoName,
  noreplyEmail: noreplyEmail
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = api;
}
